name: final-python-CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.7-slim

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Test with pytest
        run: |
          pytest -q

      - name: Create source package
        run: |
          apt-get update && apt-get install -y zip
          zip -r final-python-source.zip . -x "venv/*" ".git/*" ".pytest_cache/*"

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: final-python-source
          path: final-python-source.zip

  dockerhub_push:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag amirmn1610/final-python:$(date +%F)-${{ github.run_number }}

      - name: Docker login
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASS }}

      - name: Docker push
        run: |
          docker push amirmn1610/final-python:$(date +%F)-${{ github.run_number }}
          docker tag amirmn1610/final-python:$(date +%F)-${{ github.run_number }} amirmn1610/final-python:latest
          docker push amirmn1610/final-python:latest
